shell = { program = "C:\\Program Files\\Git\\usr\\bin\\bash.exe", args = ["--login", "-i"] }

[window]
dimensions = { columns = 230, lines = 86 }
position = { x = 1800, y = 300 }

[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
size = 11

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]