# alacritty uses wezterm's C:\Program Files\WezTerm\OpenConsole.exe, conpty.dll, (they are added to PATH on wezterm install) otherwise scrolling doesnt work in nvim
# the above files can also be found here: https://github.com/wez/wezterm/tree/main/assets/windows/conhost
# just drop them inside alacritty's .exe dir (process explorer confirms it picks up openconsole.exe, not sure about conpty.dll)
# todo: check the other dll is loaded too, it's supposed to make mapping c-space possible: https://github.com/alacritty/alacritty/issues/1703
shell = { program = "C:\\Program Files\\Git\\usr\\bin\\bash.exe", args = ["--login", "-i"] }

[window]
dimensions = { columns = 230, lines = 86 }
position = { x = 1800, y = 300 }

[font]
#normal = { family = "Source Code Pro", style = "Regular" }
#bold = { family = "Source Code Pro", style = "Semibold" }
#italic = { family = "Source Code Pro", style = "Italic" }
#bold_italic = { family = "Source Code Pro", style = "Semibold Italic" }
size = 11
normal = { family = "SauceCodePro NF", style = "Regular" }
bold = { family = "SauceCodePro NF", style = "SemiBold" }
italic = { family = "SauceCodePro NF", style = "Italic" }
bold_italic = { family = "SauceCodePro NF", style = "SemiBold Italic" }
# fix underline's line crossing the glyphs
glyph_offset = { x = 0, y = 1 }

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[debug]
#render_timer = true
#renderer = "glsl3"
#prefer_egl = true

[keyboard]
bindings = [
# c-space does not work on windows
{key = "Space", mods = "Control", chars = "\u0000"},
# c-6 is possible like this (sends ^^, can check with :<C-v>)
{ key = "Key6", mods = "Control", chars = "\u001e"},
]
