shell = { program = "C:\\Program Files\\Git\\usr\\bin\\bash.exe", args = ["--login", "-i"] }

[window]
dimensions = { columns = 230, lines = 86 }
position = { x = 1800, y = 300 }

[font]
#normal = { family = "Source Code Pro", style = "Regular" }
#bold = { family = "Source Code Pro", style = "Semibold" }
#italic = { family = "Source Code Pro", style = "Italic" }
#bold_italic = { family = "Source Code Pro", style = "Semibold Italic" }
size = 11
normal = { family = "SauceCodePro NF", style = "Regular" }
bold = { family = "SauceCodePro NF", style = "SemiBold" }
italic = { family = "SauceCodePro NF", style = "Italic" }
bold_italic = { family = "SauceCodePro NF", style = "SemiBold Italic" }

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[debug]
#render_timer = true
#renderer = "glsl3"
#prefer_egl = true

[keyboard]
bindings = [
# c-space does not work on windows
#{key = "Space", mods = "Control", chars = "\u0000"},
#{ key = "Key0", mods = "Control", chars = "\\x1b[48;5u" },
#{ key = "Key1", mods = "Control", chars = "\\x1b[49;5u" },
#{ key = "Key2", mods = "Control", chars = "\\x1b[50;5u" },
#{ key = "Key3", mods = "Control", chars = "\\x1b[51;5u" },
#{ key = "Key4", mods = "Control", chars = "\\x1b[52;5u" },
#{ key = "Key5", mods = "Control", chars =  "\u001d"},
# c-6 is possible like this (sends ^^, can check with :<C-v>)
{ key = "Key6", mods = "Control", chars = "\u001e"},
#{ key = "Key7", mods = "Control", chars = "\\x1b[55;5u" },
#{ key = "Key8", mods = "Control", chars = "\\x1b[56;5u" },
#{ key = "Key9", mods = "Control", chars = "\\x1b[57;5u" }
]
