[font]
# values for hinting: "full", "normal", "slight", "none" (default)
# values for edging: "antialias" (default), "subpixelantialias", "alias"

#normal = { family = "SauceCodePro NF", style = "Regular" }
#bold = { family = "SauceCodePro NF", style = "Medium" }
#italic = { family = "SauceCodePro NF", style = "Italic" }
#bold_italic = { family = "SauceCodePro NF", style = "Medium Italic" }

# # For Source/Sauce, use size = 15 with vim.opt.linespace = -1 in init.lua
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "Source Code Pro", style = "Regular" }
# bold = { family = "Source Code Pro", style = "Medium"}
# italic = { family = "Source Code Pro", style = "Italic"}
# bold_italic = { family = "Source Code Pro", style = "Medium Italic"}

# # Fira, use size = 15
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
# bold = { family = "FiraCode Nerd Font", style = "Medium" }
# # no italics for Fira, they will be auto-derived by neovide

# # Monaspace Krypton, not bad, 'm' could be better, 't' could be taller
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "Monaspace Krypton", style = "Light" }
# bold = { family = "Monaspace Krypton", style = "Medium"}
# italic = { family = "Monaspace Krypton", style = "Light Italic"}
# bold_italic = { family = "Monaspace Krypton", style = "Medium Italic"}

# # Cascadia - also should be configurable with direct weights (have not tried) - GOOD
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "Cascadia Mono NF", style = "Light" }
# bold = { family = "Cascadia Mono NF", style = "Regular"}
# italic = { family = "Cascadia Mono NF", style = "Light Italic"}
# bold_italic = { family = "Cascadia Mono NF", style = "Italic"}

# # JetBrains NL (no ligatures) - stretched vertically, not as clear as cascadia
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "JetBrainsMonoNL NF", style = "Light" }
# bold = { family = "JetBrainsMonoNL NF", style = "SemiBold"}
# italic = { family = "JetBrainsMonoNL NF", style = "Light Italic"}
# bold_italic = { family = "JetBrainsMonoNL NF", style = "SemiBold Italic"}

# # Gohu 14 bitmap, small size
# size = 14
# hinting = "none"
# edging = "alias"
# normal = { family = "GohuFont 14 Nerd Font", style = "Regular" }

# # terminus nerd font, bitmap, bad braces
# size = 16
# hinting = "full"
# edging = "alias"
# normal = { family = "Terminess Nerd Font", style = "Regular" }

# # Intel one mono, thicker, but shorter. Equal sign '=' bad with full hinting. To be used with: vim.opt.linespace = -3. GOOD &&
# size = 15
# hinting = "none"
# edging = "antialias"
# normal = { family = "IntoneMono Nerd Font", style = "Regular" }
# bold = { family = "IntoneMono Nerd Font", style = "Medium" }
# italic = { family = "IntoneMono Nerd Font", style = "Italic" }
# bold_italic = { family = "IntoneMono Nerd Font", style = "Medium Italic" }

# # Iosevka original, install only the separate Extended ttf fonts
# # use with vim.opt.linespace=-1
# size = 15
# hinting = "full"
# edging = "antialias"
# normal = { family = "Iosevka", style = "Light" }
# bold = { family = "Iosevka", style = "Bold" }
# italic = { family = "Iosevka", style = "Light Italic" }
# bold_italic = { family = "Iosevka", style = "Bold Italic" }

# Iosevka custom
# use with vim.opt.linespace=-1
# see our iosevka custom config for weights. Currently Light = 300, SemiLight = 350 (not picked up by neovide), Regular = 400 (neovide accepts Normal only?)
# Book = 450 (not picked up), SemiBold = 500, Bold = 600
size = 15
hinting = "full"
edging = "antialias"
normal = { family = "Iosevka Custom", style = "W350" } # Light picks up SemiLight
bold = { family = "Iosevka Custom", style = "W600" }
italic = { family = "Iosevka Custom", style = "W350 Italic" }
bold_italic = { family = "Iosevka Custom", style = "W600 Italic" }

# # TODO  <-- this should be normal
# # TODO: <-- this should be bold

[font.features]
# MonoLisa = [ "+ss01", "+ss07", "+ss11", "-calt", "+ss09", "+ss02", "+ss14", "+ss16", "+ss17" ]
# For Fira Code, disabling the "calt" feature will turn off ligatures.
"FiraCode Nerd Font" = [ "-calt" ]
"Iosevka" = [ "-calt" ]

